language: go

go:
- 1.9

branches:
  only:
  #- master
  - develop
  - /^v.*$/

install:
- go get -u github.com/golang/dep/cmd/dep

script:
- make deps
- make build
## Test
## export NewRelic API key for running testing script
- export NEW_RELIC_APIKEY=$NEW_RELIC_APIKEY
#- make test
## Test


before_deploy:
- make release

deploy:
  provider: releases
  api_key:
    secure: 
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
